#!/bin/bash
#PBS -q normal
#PBS -N serial_job
#PBS -l select=1:ncpus=170:mem=384gb
#PBS -l walltime=10:00:00
#PBS -j oe
#PBS -P personal-le0003hi

cd /home/users/ntu/le0003hi/FYP---Charging-Optimization-for-Electric-Vehicle-Fleets-using-Digital-Twins
source /home/users/ntu/le0003hi/miniconda3/etc/profile.d/conda.sh
conda activate myenv
python main.py --choice 1 --folder "" --testcase manhattan_jan2_ports --folder-name ""

